### ISSUE TITLE
downloads fine, but directories are empty

### ISSUE THREAD

**Issue by BryanChrisBrown** [leapmotion/LeapUnrealModules#1]
The files show up in windows explorer but not in unreal engine. I'm not sure what I'm doing wrong, I downloaded the source directly from https://github.com/leapmotion/LeapUnrealModules/releases

![image](https://user-images.githubusercontent.com/22871421/41780041-98ce382c-7601-11e8-8fdd-7ced60c072fe.png)

![image](https://user-images.githubusercontent.com/22871421/41780059-aca9c9ec-7601-11e8-8b0e-74fa95afd79e.png)

![image](https://user-images.githubusercontent.com/22871421/41780082-bd3de888-7601-11e8-9164-1cde3a424ca1.png)

**Comment by getnamo** [comment]
Did you click the ```LeapUnrealModules-v0.3.3-UE4.19.7z```? the source (zip) won't work due to repo using git LFS.

**Comment by BryanChrisBrown** [comment]
I was downloading source, the zipped file works fine, thanks!

**Comment by BryanChrisBrown** [comment]
I was trying to download the source before, The normal directory works fine. 

Thanks!
