### ISSUE TITLE
How to make Swip hands Gesture

### ISSUE THREAD

**Issue by eusru** [leapmotion/LeapUnrealModules#11]
i want use leapmotion to Control the content of large screen to slide up and down, left and right，not in VR just in PC

**Comment by getnamo** [comment]
related question: https://github.com/leapmotion/LeapUnreal/issues/11

**Comment by eusru** [comment]
Thank you very much for your reply, but it seems that this method is far from reaching the product level. It seems that this is not the first time you have helped me on git, friendly friend!
