### ISSUE TITLE
Maps are empty

### ISSUE THREAD

**Issue by atk-io** [leapmotion/LeapUnrealModules#12]
The example maps are empty, the actors in the maps of the different modules arent in the world, only some basic geometry. In some maps not even a pawn.

I'm testing v3.3.4 for UE4.22. Please tell me if any version does not have this problem.
Please note that I've downloaded a release, it is not the same problem as the one someone else has below.

**Comment by atk-io** [comment]
It was a problem with copying files, just copying the content folder to your project doesn't work, you need yo use the migrate tool.

**Comment by sadkl** [comment]
那怎么解决呢
