### ISSUE TITLE
Is it possible to use Leap image tracking?

### ISSUE THREAD

**Issue by radiobishop** [leapmotion/LeapUnrealModules#13]
I've seen it working in UE in previous releases, but it seems to be missing from this one.

**Comment by JimSimons-UH** [comment]
Hi radiobishop, if you're referring to passing through the camera images into unreal, this can be turned on using the SetLeapPolicyNode with LEAP_POLICY_IMAGES set to enabled, and then handling image events from the Leap component. Left and right images come in per frame as Textures.
