### ISSUE TITLE
Error during the build

### ISSUE THREAD

**Issue by Refref1990** [leapmotion/LeapUnrealModules#14]
I'm trying to fix, but i can't understand where is the issue! I have other project made with the same 
 file and until now i haven't no problem! What can be the problem? 

ERROR: Plugin 'LeapMotion' (referenced via LeapMotion.uproject) does not contain the 'LeapMotion' module, but lists it in 'C:\Program Files\Epic Games\UE_4.22\Engine\Plugins\Runtime\LeapMotion\LeapMotion.uplugin'.

**Comment by JimSimons-UH** [comment]
@Refref1990 please use git clone --recurse-submodules when cloning to get the leap plugin automatically.
