### ISSUE TITLE
TrackingTestbed.umap appears to be an asset file.

### ISSUE THREAD

**Issue by MateSteinforth** [leapmotion/LeapUnrealModules#17]
Failed to load map!
../../../../../Unreal/LEAP Motion Plugins/LeapUnrealModules-0.3.9b/Content/Modules/Debug/TrackingTestbed.umap appears to be an asset file.

all the folders are empty/content not recognized

UE4.25.4

**Comment by MateSteinforth** [comment]
Ah Ok this is because of git-lfs. the full data has not been made available to download it seams...

**Comment by MaxPalmer-UH** [comment]
Yes, we've noticed the issue with Git-LFS and are taking steps to address it.

**Comment by JimSimons-UH** [comment]
Hi @MateSteinforth. This is now fixed by adding LFS support to the zip files/archive.
