### ISSUE TITLE
I suggest an example on teleport mechanics with Leap Motion, right now it´s a bit weird :P

### ISSUE THREAD

**Issue by juangea** [leapmotion/LeapUnrealModules#2]
I suggest an example on teleport mechanics with Leap Motion, right now it´s a bit weird :P

**Comment by getnamo** [comment]
There are couple of ways to do this off the top of my head: 
1) Make a finger pointing gesture detection on one hand and then make a tap gesture with the other hand to initiate the teleport.
2) Pinch with both hands close together and then move hands outwards, when it breaches a certain distance between the hands it will teleport you. Key here is that if you want to use this gesture for something else like e.g. how [blocks](https://gallery.leapmotion.com/blocks/) demo does it, you may have to have a 'mode' switch or detect if you're not hitting anything while doing the initial pinches.
3) Don't use the leap: tap your headset and detect the tap vibrations to teleport the user to where they are looking.


Key to a good teleportation/movement system is that it needs to be both easy enough to do many times and also robust enough to not trigger accidentally.

Do you have a preference for either of the options mentioned or another system you have in mind?
