### ISSUE TITLE
Packaging to Lumin

### ISSUE THREAD

**Issue by seijihg** [leapmotion/LeapUnrealModules#6]
Hi Guys,

I am trying to package the modules project to Lumin but receiving the below error messages? Not sure how to fix it.

[errorUnreal.txt](https://github.com/leapmotion/LeapUnrealModules/files/3034388/errorUnreal.txt)

**Comment by getnamo** [comment]
Lumin is not a supported platform. You're thinking of [Magic Leap](https://docs.unrealengine.com/en-US/Platforms/AR/MagicLeap), not [Leap Motion](https://developer.leapmotion.com/).
