### ISSUE TITLE
In Debug Module the MotionControllerTracker seems not to work

### ISSUE THREAD

**Issue by Lildreas** [leapmotion/LeapUnrealModules#7]
First thanks for your effort!

I just started to work with Leap Motion, I put it on the VIVE Pro headset.

I wanted to create a scene where I can see the VIVE Pro motion controllers and the hands scanned bei Leap Motion. I looked at the Debug Module and I guess this should be the perfect example, but the MotionControllerTracker doesn't get transformation updates from the physical controllers. 

When I did my own testing I could track my hands with Leap Motion OR I could track the motion controllers set to a Pawn the was possesed by Player 0. But I couldn't do both at the same time. 

Thanks & best from Munich, Germany
Andreas

**Comment by getnamo** [comment]
The _MotionControllerTracker_ blueprint actor simply takes [motion controller components](https://docs.unrealengine.com/en-US/Platforms/VR/DevelopVR/MotionController/index.html) set to Left/Right with cubes attached. If the origin of the actor is the same as your pawn, they will track from the same origin and you can visualize tracking fidelity in comparison when holding the controllers. 

It is encouraged to set your tracking origin to 'floor' for all hmds.

![image](https://user-images.githubusercontent.com/542365/59526905-f5b08f80-8e8e-11e9-954d-06ea1d701f73.png)


To get what you're looking for, I'd probably duplicate the leap hands pawn, add the motion controller components directly to your pawn and add the models of the controllers as child scene nodes for each of the motion controller components. 

If you're still using the motion controller tracker actor you may want to delete ```MoveUpForOculus``` it may be mis-identifying your pro headset and adding an offset. It should be safe to delete that node.

![image](https://user-images.githubusercontent.com/542365/59526938-0e20aa00-8e8f-11e9-9767-78eea0d69cef.png)

**Comment by Lildreas** [comment]
Thanks for the detailed answer!
Best
Andreas
