### ISSUE TITLE
is:issue is:open Guys I need your help, I cannot touch the objects by leap hands, what can I do? Grab/Release is working well. but can't touch the things, its going through the box :(

### ISSUE THREAD

**Issue by Timurpc** [leapmotion/LeapUnrealModules#8]

**Comment by Timurpc** [comment]
you can contact me by timur2322727@gmail.com

**Comment by getnamo** [comment]
Sounds like you need to add a physics asset to the target mesh (see https://docs.unrealengine.com/en-US/Engine/Physics/PhysicsAssetEditor/index.html). This will change how grab/release works though as the block will sometimes get pushed away before being able to grasp.

**Comment by Timurpc** [comment]
Actually I want to touch the box only (static mesh) as you touch in your video at the beginning( Jenga part 2 05:58-06:00min), even its not working. I can grab with Oculus rift controllers but not with LeapMotion. I checked physics and collision. If you have skype I can show by screen sharing.

**Comment by Timurpc** [comment]
> Sounds like you need to add a physics asset to the target mesh (see https://docs.unrealengine.com/en-US/Engine/Physics/PhysicsAssetEditor/index.html). This will change how grab/release works though as the block will sometimes get pushed away before being able to grasp.

If you have a project with starter content only, can you send me (including pawn, blueprint and box)? Please! (extra information if needed: I'm using UE4.22 VR with Oculus rift).
